#!/bin/bash
# Create Pull Request Only
#
# This script is called by verify.yml workflow after all tests pass
# to create a PR without transitioning the ticket (ticket is already in VERIFY).
#
# Usage: create-pr-only.sh <ticket_id> <project_id> <branch> <app_url> <workflow_api_token>

set -e

# Parse arguments
TICKET_ID=$1
PROJECT_ID=$2
BRANCH=$3
APP_URL=$4
WORKFLOW_API_TOKEN=$5

# Validate required arguments
if [ -z "$TICKET_ID" ] || [ -z "$PROJECT_ID" ] || [ -z "$BRANCH" ] || [ -z "$APP_URL" ] || [ -z "$WORKFLOW_API_TOKEN" ]; then
  echo "❌ Error: Missing required arguments"
  echo "Usage: $0 <ticket_id> <project_id> <branch> <app_url> <workflow_api_token>"
  exit 1
fi

echo "📋 Creating Pull Request..."
echo "  Ticket ID: $TICKET_ID"
echo "  Project ID: $PROJECT_ID"
echo "  Branch: $BRANCH"

# Verify branch exists on remote before creating PR
echo ""
echo "🔍 Verifying branch exists on remote..."
if ! git ls-remote --exit-code --heads origin "${BRANCH}" >/dev/null 2>&1; then
  echo "❌ Error: Branch '${BRANCH}' does not exist on remote"
  echo "   This should not happen - branch should have been pushed in previous step"
  exit 1
fi
echo "✅ Branch exists on remote: ${BRANCH}"

# Create Pull Request (branch is already pushed by previous workflow step)
echo ""
echo "🔀 Creating Pull Request..."
echo "Debug - GH CLI environment:"
echo "  GH_TOKEN set: $([ -n "$GH_TOKEN" ] && echo "yes (length: ${#GH_TOKEN})" || echo "no")"
echo "  gh version: $(gh --version | head -n1)"
echo "  gh auth status:"
gh auth status 2>&1 || echo "  ⚠️ gh auth check failed"
echo ""

PR_CREATE_OUTPUT=$(gh pr create \
  --title "feat(${TICKET_ID}): automated implementation" \
  --body "## 🤖 Automated Implementation

This pull request was automatically generated by the AI Board implementation workflow.

**Ticket**: #${TICKET_ID}
**Branch**: \`${BRANCH}\`
**Workflow**: Spec-Kit Implementation

### What's Changed
Implementation completed by Claude Code based on the feature specification.

### Testing
✅ All tests passed in the verify workflow

### Review Checklist
- [ ] Code changes align with ticket requirements
- [ ] Tests pass successfully
- [ ] No merge conflicts
- [ ] Ready to merge

---

🤖 Generated with [Claude Code](https://claude.com/claude-code)" \
  --base main \
  --head "${BRANCH}" 2>&1)

PR_CREATE_EXIT=$?

if [ $PR_CREATE_EXIT -eq 0 ]; then
  PR_URL="$PR_CREATE_OUTPUT"
  echo "✅ Pull Request created: ${PR_URL}"
else
  echo "⚠️ PR creation failed (exit code: $PR_CREATE_EXIT)"
  echo "   Full output: ${PR_CREATE_OUTPUT}"
  echo ""
  echo "Debug information:"
  echo "  Current branch: $(git rev-parse --abbrev-ref HEAD)"
  echo "  Target branch: ${BRANCH}"
  echo "  Base branch: main"
  echo "  Remote branches: $(git ls-remote --heads origin | grep -F "${BRANCH}" || echo "not found")"
  echo "  GH_TOKEN set: $([ -n "$GH_TOKEN" ] && echo "yes (length: ${#GH_TOKEN})" || echo "no")"
  echo "  Repository: $(git config --get remote.origin.url)"
  echo ""
  echo "   Checking if PR already exists..."

  # Try to get existing PR URL
  PR_URL=$(gh pr view "${BRANCH}" --json url -q '.url' 2>&1)
  PR_VIEW_EXIT=$?

  if [ $PR_VIEW_EXIT -ne 0 ]; then
    echo "❌ Error: Could not find existing PR either"
    echo "   gh pr view output: ${PR_URL}"
    exit 1
  fi

  echo "✅ Found existing PR: ${PR_URL}"
fi

if [ -n "$PR_URL" ]; then
  PR_NUMBER=$(gh pr view "${BRANCH}" --json number -q '.number' 2>/dev/null || echo "")
  echo "✅ Pull Request: ${PR_URL}"

  # Post comment with PR link
  echo ""
  echo "💬 Posting PR notification comment..."

  # Build the JSON payload properly - use jq for proper JSON escaping
  COMMENT_CONTENT="✅ **Pull Request Ready for Review**

**PR #${PR_NUMBER}**: [View Pull Request](${PR_URL})

The implementation is complete and all tests have passed.

**Next Steps**:
- Review the code changes
- Approve and merge when ready"

  # Create JSON payload using jq for proper escaping (if available), otherwise use python
  if command -v jq >/dev/null 2>&1; then
    JSON_PAYLOAD=$(echo "$COMMENT_CONTENT" | jq -Rs --arg userId "ai-board-system-user" '{content: ., userId: $userId}')
  elif command -v python3 >/dev/null 2>&1; then
    JSON_PAYLOAD=$(echo "$COMMENT_CONTENT" | python3 -c "
import json
import sys
content = sys.stdin.read()
payload = {'content': content, 'userId': 'ai-board-system-user'}
print(json.dumps(payload))
")
  else
    # Fallback to manual escaping (less reliable but works in most cases)
    ESCAPED_CONTENT=$(echo "$COMMENT_CONTENT" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | awk '{printf "%s\\n", $0}' | sed 's/\\n$//')
    JSON_PAYLOAD="{\"content\": \"${ESCAPED_CONTENT}\", \"userId\": \"ai-board-system-user\"}"
  fi

  curl -X POST "${APP_URL}/api/projects/${PROJECT_ID}/tickets/${TICKET_ID}/comments/ai-board" \
    -H "Authorization: Bearer ${WORKFLOW_API_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$JSON_PAYLOAD" \
    -f -s -S || echo "⚠️ Failed to post PR comment (continuing...)"
else
  echo "⚠️ Could not determine PR URL"
fi

echo ""
echo "✅ Pull Request created successfully!"
